### ISSUE TITLE
max_ntree_per_split is 0

### ISSUE THREAD

**Issue by meditations** [motefly/DeepGBM#18]
It seems the max_ntree_per_split is not properly initiated, and it's always 0.

Traceback (most recent call last):
  File "main.py", line 102, in <module>
    main()
  File "main.py", line 94, in main
    train_DEEPGBM(args, num_data, cate_data, plot_title, key="")
  File "/Users/binrong/Desktop/Code/DeepGBM/experiments/train_models.py", line 165, in train_DEEPGBM
    emb_model = EmbeddingModel(n_models, max_ntree_per_split, args.embsize, args.maxleaf+1, n_output, group_average, task=args.task).to(device)
  File "/Users/binrong/Desktop/Code/DeepGBM/experiments/models/components.py", line 230, in __init__
    stdv = math.sqrt(1.0 /(max_ntree_per_split))
ZeroDivisionError: float division by zero

**Comment by motefly** [comment]
Thanks, there may be some corner cases that make it an error, please consider fixing it in your code.
